name: Release 

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build -t 19127098/nest-app .
    - run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p {{secrets.DOCKER_HUB_PASSWORD}}
    - run: docker push 19127098/nest-app
